### ISSUE TITLE
pip-tools missing

### ISSUE THREAD

**Issue by mering** [renovatebot/base-image#1261]
We now get the following error for the `pip-compile` module via GitHub Action while it worked previously and the logs also tell that it installed this tool successfully:
```
Command failed: pip-compile --generate-hashes --output-file=requirements.txt requirements.in
Traceback (most recent call last):
  File "/opt/containerbase/tools/pip-tools/7.4.1/3.11.10/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/containerbase/tools/pip-tools/7.4.1/3.11.10/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pip-tools/7.4.1/3.11.10/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pip-tools/7.4.1/3.11.10/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pip-tools/7.4.1/3.11.10/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pip-tools/7.4.1/3.11.10/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pip-tools/7.4.1/3.11.10/lib/python3.11/site-packages/piptools/scripts/compile.py", line 465, in cli
    cache=DependencyCache(cache_dir),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pip-tools/7.4.1/3.11.10/lib/python3.11/site-packages/piptools/cache.py", line 71, in __init__
    os.makedirs(cache_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.cache/pip-tools'
```

**Comment by viceice** [comment]
wrong repo. please ask on main repo discussions for help.

the latest renovate image should solve the issue
